name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-spec:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm i

      - name: Test
        run: npm run test

      - name: Build Docs
        run: npm run build:docs

      - name: Deploy test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
